version: '3.4'

services:
  bossaboxchallenge:
    image: bossaboxchallenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "8181:8181"
    command: npm run start
